### ISSUE TITLE
Not able to locate configuration file

### ISSUE THREAD

**Issue by VINIT777** [studiogangster/sensibull-realtime-options-api-ingestor#2]
Can you help me in locating config file where i need to update instrument & sensibull credentials?
Also does it need sensibull premium?

**Comment by studiogangster** [comment]
No need to provide credentials. It will work without it. Just spin the docker-container.
By default, realtime data for all the  instruments are pulled. 
To customise it, you can update the list of instruments in file:
https://github.com/studiogangster/sensibull-realtime-options-api-ingestor/blob/main/realtime-data/instruments_symbols.js

**Comment by VINIT777** [comment]
Thanks for the response - I have few more questions on getting started:
After the docker compose -up - inside the container i did npm start - now this is the output which I got

<img width="367" alt="image" src="https://github.com/studiogangster/sensibull-realtime-options-api-ingestor/assets/6377528/25ec131f-0180-4e55-bb7f-eb58892b5f7e">

What should i do post this?

**Comment by VINIT777** [comment]
I am trying to get OI data for say reliance - so i have kept only one instrument in instruments symbol.js as below

<img width="540" alt="image" src="https://github.com/studiogangster/sensibull-realtime-options-api-ingestor/assets/6377528/5d935b30-d9b4-4b66-9ad7-4bd4d863902c">

Do I Need to change anything here as well?

**Comment by studiogangster** [comment]
After spinning up the docker, , look for ".data" directory in the root  of project.
It should have the feeds of all the instruments in jsonl format.

".data" is hidden (since it starts with a dot), look for all folders: ls -alh

**Comment by VINIT777** [comment]
Thanks for responding - I am able to see data now - but I tried to modify the instrument to get weekly expiry for 22000 strike price for nifty - but it is still pulling data for all the strike prices - also how to know if the pulled data is for monthly or weekly option - please review below :


```
const instruments =  [
    {
      "instrument_token": 256265,
      "name": "NIFTY 50",
      "tradingsymbol": "NIFTY",
      "underlying_instrument": "NIFTY",
      "expiry": "WEEKLY",
      "strike": 22000,
      "tick_size": 0,
      "lot_size": 0,
      "multiplier": 1,
      "is_underlying": true,
      "is_non_fno": false,
      "tradable": false,
      "broker": "2",
      "mode": "full",
      "exchange": "NSE",
      "segment": "NSE-INDICES",
      "instrument_type": "EQ",
      "last_price": 18877.7,
      "last_updated_at": "2023-10-26T12:47:59+05:30",
      "last_traded_timestamp": 0,
      "sectors": [
        "Index"
      ]
      }
    ];
```

**Comment by VINIT777** [comment]
What modification do i need to do above to get NIFTY 22000 Weekly expiry data?

**Comment by studiogangster** [comment]
For each instrument, aggregated data is collected at once, for every tick.
So, on each line, you will be getting details for all the strike prices.
Further, you can filter out the data as per the requirement.

**Comment by studiogangster** [comment]
Currently due to an urgent work, I am unable to update the repo. Will soon integrate weekly expiry in the next release.

**Comment by shikharvaish28** [comment]
@studiogangster came across your work - it's beautifully done. Kudos!
